def print_map(content, k):
    print(
        content.format(
            k["Green Lich"][0],
            k["Red Lich"][0],
            k["Argent Tournament"][0],
            k["Argent Tournament"][1],
            k["Argent Tournament"][2],
            k["Temple of Storms"][0],
            k["Temple of Storms"][1],
            k["Temple of Storms"][2],
            k["Ulduar"][0],
            k["Ulduar"][1],
            k["Ulduar"][2],
            k["Green Lich"][1],
            k["Red Lich"][1],
            k["Argent Tournament"][3],
            k["Argent Tournament"][4],
            k["Argent Tournament"][5],
            k["Temple of Storms"][3],
            k["Temple of Storms"][4],
            k["Temple of Storms"][5],
            k["Ulduar"][4],
            k["Ulduar"][5],
            k["Ulduar"][5],
            k["Green Lich"][2],
            k["Red Lich"][2],
            k["Argent Tournament"][6],
            k["Argent Tournament"][7],
            k["Argent Tournament"][8],
            k["Temple of Storms"][6],
            k["Temple of Storms"][7],
            k["Temple of Storms"][8],
            k["Ulduar"][6],
            k["Ulduar"][7],
            k["Ulduar"][8],
            k["Green Lich"][3],
            k["Red Lich"][3],
            k["Green Lich"][4],
            k["Red Lich"][4],
            k["Shadow Vault"][0],
            k["Shadow Vault"][1],
            k["Shadow Vault"][2],
            k["The Breach"][0],
            k["The Breach"][1],
            k["The Breach"][2],
            k["Green Lich"][5],
            k["Red Lich"][5],
            k["Shadow Vault"][3],
            k["Shadow Vault"][4],
            k["Shadow Vault"][5],
            k["The Breach"][3],
            k["The Breach"][4],
            k["The Breach"][5],
            k["Green Lich"][6],
            k["Red Lich"][6],
            k["Shadow Vault"][6],
            k["Shadow Vault"][7],
            k["Shadow Vault"][8],
            k["The Breach"][6],
            k["The Breach"][7],
            k["The Breach"][8],
            k["Green Lich"][7],
            k["Red Lich"][7],
            k["Onslaught Harbor"][0],
            k["Onslaught Harbor"][1],
            k["Onslaught Harbor"][2],
            k["Terrace of the Makers"][0],
            k["Terrace of the Makers"][1],
            k["Terrace of the Makers"][2],
            k["Green Lich"][8],
            k["Red Lich"][8],
            k["Onslaught Harbor"][3],
            k["Onslaught Harbor"][4],
            k["Onslaught Harbor"][5],
            k["Terrace of the Makers"][3],
            k["Terrace of the Makers"][4],
            k["Terrace of the Makers"][5],
            k["Onslaught Harbor"][6],
            k["Onslaught Harbor"][7],
            k["Onslaught Harbor"][8],
            k["Terrace of the Makers"][6],
            k["Terrace of the Makers"][7],
            k["Terrace of the Makers"][8],
            k["Thunderfall"][0],
            k["Thunderfall"][1],
            k["Thunderfall"][2],
            k["Thunderfall"][3],
            k["Thunderfall"][4],
            k["Thunderfall"][5],
            k["The Avalanche"][0],
            k["The Avalanche"][1],
            k["The Avalanche"][2],
            k["Icecrown Citadel"][0],
            k["Icecrown Citadel"][1],
            k["Icecrown Citadel"][2],
            k["Icecrown Citadel"][3],
            k["Thunderfall"][6],
            k["Thunderfall"][7],
            k["Thunderfall"][8],
            k["Gundrak"][0],
            k["Gundrak"][1],
            k["Gundrak"][2],
            k["The Avalanche"][3],
            k["The Avalanche"][4],
            k["The Avalanche"][5],
            k["Icecrown Citadel"][4],
            k["Icecrown Citadel"][5],
            k["Icecrown Citadel"][6],
            k["Icecrown Citadel"][7],
            k["Gundrak"][3],
            k["Gundrak"][4],
            k["Gundrak"][5],
            k["Purple Lich"][0],
            k["The Avalanche"][6],
            k["The Avalanche"][7],
            k["The Avalanche"][8],
            k["Icecrown Citadel"][8],
            k["Icecrown Citadel"][9],
            k["Icecrown Citadel"][10],
            k["Icecrown Citadel"][11],
            k["Gundrak"][6],
            k["Gundrak"][7],
            k["Gundrak"][8],
            k["Purple Lich"][1],
            k["Frosthold"][0],
            k["Frosthold"][1],
            k["Frosthold"][2],
            k["Purple Lich"][2],
            k["Frosthold"][3],
            k["Frosthold"][4],
            k["Frosthold"][5],
            k["Thrym's End"][0],
            k["Thrym's End"][1],
            k["Thrym's End"][2],
            k["Purple Lich"][3],
            k["River's Heart"][0],
            k["River's Heart"][1],
            k["River's Heart"][2],
            k["Vault of Archavon"][0],
            k["Vault of Archavon"][1],
            k["Vault of Archavon"][2],
            k["Dalaran"][0],
            k["Dalaran"][1],
            k["Dalaran"][2],
            k["Frosthold"][6],
            k["Frosthold"][7],
            k["Frosthold"][8],
            k["Thrym's End"][3],
            k["Thrym's End"][4],
            k["Thrym's End"][5],
            k["Kolramas"][0],
            k["Kolramas"][1],
            k["Kolramas"][2],
            k["Purple Lich"][4],
            k["River's Heart"][3],
            k["River's Heart"][4],
            k["River's Heart"][5],
            k["Vault of Archavon"][3],
            k["Vault of Archavon"][4],
            k["Vault of Archavon"][5],
            k["Dalaran"][3],
            k["Dalaran"][4],
            k["Dalaran"][5],
            k["Thrym's End"][6],
            k["Thrym's End"][7],
            k["Thrym's End"][8],
            k["Kolramas"][3],
            k["Kolramas"][4],
            k["Kolramas"][5],
            k["Purple Lich"][5],
            k["River's Heart"][6],
            k["River's Heart"][7],
            k["River's Heart"][8],
            k["Vault of Archavon"][6],
            k["Vault of Archavon"][7],
            k["Vault of Archavon"][8],
            k["Dalaran"][6],
            k["Dalaran"][7],
            k["Dalaran"][8],
            k["Kolramas"][6],
            k["Kolramas"][7],
            k["Kolramas"][8],
            k["Purple Lich"][6],
            k["Purple Lich"][7],
            k["Drak'Tilaron Keep"][0],
            k["Drak'Tilaron Keep"][1],
            k["Drak'Tilaron Keep"][2],
            k["Purple Lich"][8],
            k["The Nexus"][0],
            k["The Nexus"][1],
            k["The Nexus"][2],
            k["Temple City of En'Kilah"][0],
            k["Temple City of En'Kilah"][1],
            k["Temple City of En'Kilah"][2],
            k["The Wrathgate"][0],
            k["The Wrathgate"][1],
            k["The Wrathgate"][2],
            k["Drak'Tilaron Keep"][3],
            k["Drak'Tilaron Keep"][4],
            k["Drak'Tilaron Keep"][5],
            k["Grizzlemaw"][0],
            k["Grizzlemaw"][1],
            k["Grizzlemaw"][2],
            k["The Nexus"][3],
            k["The Nexus"][4],
            k["The Nexus"][5],
            k["Temple City of En'Kilah"][3],
            k["Temple City of En'Kilah"][4],
            k["Temple City of En'Kilah"][5],
            k["The Wrathgate"][3],
            k["The Wrathgate"][4],
            k["The Wrathgate"][5],
            k["Naxxramas"][0],
            k["Naxxramas"][1],
            k["Naxxramas"][2],
            k["Drak'Tilaron Keep"][6],
            k["Drak'Tilaron Keep"][7],
            k["Drak'Tilaron Keep"][8],
            k["Grizzlemaw"][3],
            k["Grizzlemaw"][4],
            k["Grizzlemaw"][5],
            k["The Nexus"][6],
            k["The Nexus"][7],
            k["The Nexus"][8],
            k["Temple City of En'Kilah"][6],
            k["Temple City of En'Kilah"][7],
            k["Temple City of En'Kilah"][8],
            k["The Wrathgate"][6],
            k["The Wrathgate"][7],
            k["The Wrathgate"][8],
            k["Naxxramas"][3],
            k["Naxxramas"][4],
            k["Naxxramas"][5],
            k["Grizzlemaw"][6],
            k["Grizzlemaw"][7],
            k["Grizzlemaw"][8],
            k["Vengeance Landing"][0],
            k["Vengeance Landing"][1],
            k["Vengeance Landing"][2],
            k["Naxxramas"][6],
            k["Naxxramas"][7],
            k["Naxxramas"][8],
            k["Vengeance Landing"][3],
            k["Vengeance Landing"][4],
            k["Vengeance Landing"][5],
            k["Vengeance Landing"][6],
            k["Vengeance Landing"][7],
            k["Vengeance Landing"][8],
            k["Warsong Hold"][0],
            k["Warsong Hold"][1],
            k["Warsong Hold"][2],
            k["Azjol-Nerub"][0],
            k["Azjol-Nerub"][1],
            k["Azjol-Nerub"][2],
            k["Wyrmrest Temple"][0],
            k["Wyrmrest Temple"][1],
            k["Wyrmrest Temple"][2],
            k["Amberpine Lodge"][0],
            k["Amberpine Lodge"][1],
            k["Amberpine Lodge"][2],
            k["Warsong Hold"][3],
            k["Warsong Hold"][4],
            k["Warsong Hold"][5],
            k["Azjol-Nerub"][3],
            k["Azjol-Nerub"][4],
            k["Azjol-Nerub"][5],
            k["Wyrmrest Temple"][3],
            k["Wyrmrest Temple"][4],
            k["Wyrmrest Temple"][5],
            k["Amberpine Lodge"][3],
            k["Amberpine Lodge"][4],
            k["Amberpine Lodge"][5],
            k["Utgarde Keep"][0],
            k["Utgarde Keep"][1],
            k["Utgarde Keep"][2],
            k["Warsong Hold"][6],
            k["Warsong Hold"][7],
            k["Warsong Hold"][8],
            k["Valiance Keep"][0],
            k["Valiance Keep"][1],
            k["Valiance Keep"][2],
            k["Azjol-Nerub"][6],
            k["Azjol-Nerub"][7],
            k["Azjol-Nerub"][8],
            k["Wyrmrest Temple"][6],
            k["Wyrmrest Temple"][7],
            k["Wyrmrest Temple"][8],
            k["Amberpine Lodge"][6],
            k["Amberpine Lodge"][7],
            k["Amberpine Lodge"][8],
            k["Utgarde Keep"][3],
            k["Utgarde Keep"][4],
            k["Utgarde Keep"][5],
            k["Valiance Keep"][3],
            k["Valiance Keep"][4],
            k["Valiance Keep"][5],
            k["Utgarde Keep"][6],
            k["Utgarde Keep"][7],
            k["Utgarde Keep"][8],
            k["Valgarde"][0],
            k["Valgarde"][1],
            k["Valgarde"][2],
            k["Valiance Keep"][6],
            k["Valiance Keep"][7],
            k["Valiance Keep"][8],
            k["Valgarde"][3],
            k["Valgarde"][4],
            k["Valgarde"][5],
            k["Valgarde"][6],
            k["Valgarde"][7],
            k["Valgarde"][8],
        )
    )
